apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastkubefy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/jcpurger/fastkubefy-gitops.git
    targetRevision: main
    path: apps/fastkubefy

  destination:
    server: https://kubernetes.default.svc
    namespace: fastkubefy

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m